include:
    - project: i40/administration
      file: gitlab-ci-maven.yml
      ref: main

variables:
  MVN_FORBID_SNAPSHOT_DEPENDENCIES_DISABLED : "true"
  MAVEN_DEPLOY_FROM_UNPROTECTED_DISABLED: "true"
  MAVEN_DEPLOY_ENABLED: "true"
    
docker-publish-baxter:
  extends: .docker-publish-module
  variables:
    MODULE_NAME: baxter

docker-publish-drone:
  extends: .docker-publish-module
  variables:
    MODULE_NAME: drone

docker-publish-laplaser:
  extends: .docker-publish-module
  variables:
    MODULE_NAME: laplaser

docker-publish-mir:
  extends: .docker-publish-module
  variables:
    MODULE_NAME: mir

docker-publish-smartwatch:
  extends: .docker-publish-module
  variables:
    MODULE_NAME: smartwatch

docker-publish-ur:
  extends: .docker-publish-module
  variables:
    MODULE_NAME: ur

docker-publish-vacuum:
  extends: .docker-publish-module
  variables:
    MODULE_NAME: vacuum

docker-publish-virtual:
  extends: .docker-publish-module
  variables:
    MODULE_NAME: virtual

docker-publish-wallet:
  extends: .docker-publish-module
  variables:
    MODULE_NAME: wallet

docker-publish-worker:
  extends: .docker-publish-module
  variables:
    MODULE_NAME: worker
