image: maven:3-eclipse-temurin-11-alpine

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
  - test
  #- deploy
  - publish

build:
  stage: build
  tags:
    - basys
    - maven
  script:
    - mvn -V $MAVEN_CLI_OPTS compile

test:
  stage: test
  tags:
    - basys
    - maven
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  tags:
    - basys
    - maven
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master
    - develop

docker:
  stage: publish
  image: dfkibasys/docker-temurin11jdk:20.10.12
  services:
    - docker:20.10.12-dind
  tags:
    - basys
    - docker
  before_script:
    - docker info
  script:
    - chmod 775 ./mvnw
    - ./mvnw $MAVEN_CLI_OPTS -Ddocker_username=$DOCKER_REGISTRY_USER -Ddocker_password=$DOCKER_REGISTRY_PASSWORD spring-boot:build-image
  only:
    - master
    - develop
