# Step : Package (skip tests)
FROM maven:3.5.3-jdk-8-alpine as builder
COPY . /build
WORKDIR /build
RUN mvn -s settings_basys.xml clean package -DskipTests -P ccs

# Step : Build image
FROM openjdk:8-jre-alpine
LABEL maintainer="basys-support@dfki.de"
EXPOSE 5082
COPY --from=builder /build/configs/default/de.dfki.cos.basys.p4p.config.default.ccs/target/*jar-with-dependencies.jar /app/basys-cc-server.jar
COPY --from=builder /build/configs/default/de.dfki.cos.basys.p4p.config.default.ccs/components /app/components
COPY --from=builder /build/configs/default/de.dfki.cos.basys.p4p.config.default.ccs/components_repo /app/components_repo
COPY --from=builder /build/configs/default/de.dfki.cos.basys.p4p.config.default.ccs/config /app/config
COPY --from=builder /build/configs/default/de.dfki.cos.basys.p4p.config.default.ccs/certs /app/certs
WORKDIR /app
#ENV JAVA_OPTS="-Dlog4j.configuration=file:///app/config/log4j.properties"
ENTRYPOINT ["java", "-Dlog4j.configuration=file:///app/config/log4j.properties", "-jar","./basys-cc-server.jar"]
