# Step : Package (skip tests)
FROM maven:3.5.3-jdk-8-alpine as builder
COPY . /build
WORKDIR /build
RUN mvn -s settings_basys.xml clean package -DskipTests -P aas

# Step : Build image
FROM openjdk:8-jre-alpine
LABEL maintainer="basys-support@dfki.de"
EXPOSE 4999 5080 5081
COPY --from=builder /build/configs/default/de.dfki.cos.basys.p4p.config.default.aas/target/*jar-with-dependencies.jar /app/basys-aas-services.jar
COPY --from=builder /build/configs/default/de.dfki.cos.basys.p4p.config.default.aas/components /app/components
COPY --from=builder /build/configs/default/de.dfki.cos.basys.p4p.config.default.aas/components_repo /app/components_repo
COPY --from=builder /build/configs/default/de.dfki.cos.basys.p4p.config.default.aas/config /app/config
WORKDIR /app
#ENV JAVA_OPTS="-Dlog4j.configuration=file:///app/config/log4j.properties"
ENTRYPOINT ["java", "-Dlog4j.configuration=file:///app/config/log4j.properties", "-jar","./basys-aas-services.jar"]
