# Step : Package (skip tests)
FROM maven:3.5.3-jdk-8-alpine as builder
COPY . /build
WORKDIR /build
RUN mvn -s settings_basys.xml clean package -DskipTests -P platform

# Step : Build image
FROM openjdk:8-jre-alpine
LABEL maintainer="basys-support@dfki.de"
EXPOSE 5083
COPY --from=builder /build/configs/default/de.dfki.cos.basys.p4p.config.default.platform/target/*jar-with-dependencies.jar /app/basys-platform.jar
COPY --from=builder /build/configs/default/de.dfki.cos.basys.p4p.config.default.platform/components /app/components
COPY --from=builder /build/configs/default/de.dfki.cos.basys.p4p.config.default.platform/components_repo /app/components_repo
COPY --from=builder /build/configs/default/de.dfki.cos.basys.p4p.config.default.platform/config /app/config
COPY --from=builder /build/configs/default/de.dfki.cos.basys.p4p.config.default.platform/processes /app/processes
COPY --from=builder /build/configs/default/de.dfki.cos.basys.p4p.config.default.platform/model /app/model
WORKDIR /app
#ENV JAVA_OPTS="-Dlog4j.configuration=file:///app/config/log4j.properties"
ENTRYPOINT ["java", "-Dlog4j.configuration=file:///app/config/log4j.properties", "-jar","./basys-platform.jar"]
