basys:
  opcuaServer:
    certsFolder: ./certs
    tcpPort: 12685
    httpsPort: 8443
  controlcomponent:
    id: binpicking_1
    name: BinPickingStation-1
    operationModeJavaPackage: de.dfki.cos.basys.p4p.controlcomponent.binpicking.opmodes
    initialExecutionMode: SIMULATE
    executionModes:
      auto:
        executionModeChangeDisabled: false
        occupationCheckDisabled: false
        service:
          implementationJavaClass: de.dfki.cos.basys.p4p.controlcomponent.binpicking.service.BinPickingServiceImpl
          connectionString: tcp://10.6.0.50:1883
      simulate:
        executionModeChangeDisabled: true
        occupationCheckDisabled: true
