basys:
  opcuaServer:
    certsFolder: ./certs
    tcpPort: 12685
    httpsPort: 8443
  controlcomponent:
    id: vacuum_1
    name: Vacuum-1
    operationModeJavaPackage: de.dfki.cos.basys.p4p.controlcomponent.vacuum.opmodes
    initialExecutionMode: SIMULATE
    executionsModes:
      auto:
        executionModeChangeDisabled: false
        occupationCheckDisabled: false
        service:
          implementationJavaClass: de.dfki.cos.basys.p4p.controlcomponent.vacuum.service.VacuumServiceImpl
          connectionString: tcp://10.2.10.1:1883
      simulate:
        executionModeChangeDisabled: true
        occupationCheckDisabled: true