basys:
  controlcomponent:
    executionModes:
      simulate:
        executionModeChangeDisabled: false
        occupationCheckDisabled: true
        service:
          implementationJavaClass: de.dfki.cos.basys.p4p.controlcomponent.mir.service.MirServiceROSImpl
          connectionString: ws://basys-lnv-1.mrk40.dfki.lan:9200
          properties:
            gotoServerName: movsym/mir100_1
            gotoActionName: simrk40_msgs/MoveToSymbolicPositionAction
            pickServerName: picksym/mir100_1
            pickActionName: simrk40_msgs/AGVPickSymbolicAction
            dropServerName: placesym/mir100_1
            dropActionName: simrk40_msgs/AGVPlaceSymbolicAction

