logging:
  level:
    org.springframework.boot.autoconfigure: INFO
server:
  port: 8088
  accessibleEndpoint: http://localhost:8088
management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"
basys:
  aasRegistry:
    type: dotaas
    service:
      connectionString: http://localhost:8080
  eventTransmitter:
    type: mqtt
    service:
      implementationJavaClass: de.dfki.cos.basys.aas.event.mqtt.MqttEventTransmitter
      connectionString: tcp://localhost:1883
