basys:
  opcuaServer:
    certsFolder: ./certs
    tcpPort: 12685
    httpsPort: 8443
  controlcomponent:
    id: baxter_1
    name: Baxter-1
    operationModeJavaPackage: de.dfki.cos.basys.p4p.controlcomponent.baxter.opmodes
    initialExecutionMode: SIMULATE
    executionsModes:
      auto:
        executionModeChangeDisabled: false
        occupationCheckDisabled: false
        service:
          implementationJavaClass: de.dfki.cos.basys.p4p.controlcomponent.baxter.service.BaxterServiceImpl
          connectionString: ws://10.2.1.11:9090
          properties:
            serverName: /move_base
            actionNameMove: /move_base_msgs/MoveBaseAction
      simulate:
        executionModeChangeDisabled: true
        occupationCheckDisabled: true