basys:
  opcuaServer:
    certsFolder: ./certs
    tcpPort: 12699
    httpsPort: 8443
  controlcomponent:
    id: galaxy_watch_4_classic_1
    name: Galaxy-Watch-4-Classic-1
    operationModeJavaPackage: de.dfki.cos.basys.p4p.controlcomponent.smartwatch.v2.opmodes
    initialExecutionMode: AUTO
    executionModes:
      auto:
        executionModeChangeDisabled: false
        occupationCheckDisabled: false
        service:
          implementationJavaClass: de.dfki.cos.basys.p4p.controlcomponent.smartwatch.v2.service.SmartwatchMQTTServiceImpl
          connectionString: tcp://10.2.10.1:1883
          properties:
            mqttUsername: "smartwatch_v2_control_component"
            mqttPassword: "smartwatch_v2_control_component"
      simulate:
        executionModeChangeDisabled: true
        occupationCheckDisabled: true
