logging:
  level:
    org.springframework.boot.autoconfigure: INFO
management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"
server:
  port: 8088
  accessibleEndpoint: http://localhost:8088
basys:
  aasRegistry:
    type: dotaas
    service:
      connectionString: http://aasregistry.basys-lnv-1.mrk40.dfki.lan
  eventTransmitter:
    type: mqtt
    service:
      implementationJavaClass: de.dfki.cos.basys.aas.event.mqtt.MqttEventTransmitter
      connectionString: tcp://basys-lnv-1.mrk40.dfki.lan:1883
  opcuaServer:
    certsFolder: ./certs
    tcpPort: 12685
    httpsPort: 8443
  controlcomponent:
    id: drone_1
    name: Drone-1
    operationModeJavaPackage: de.dfki.cos.basys.p4p.controlcomponent.drone.opmodes
    executionMode: AUTO
    auto:
      disableExecutionModeChange: false
      disableOccupationCheck: false
      service:
        implementationJavaClass: de.dfki.cos.basys.p4p.controlcomponent.drone.service.DroneServiceImpl
        connectionString: tcp://10.2.10.1:1883
        droneInspectionServiceEndpoint: http://10.2.0.18:5000
        mqttUsername: "drone_control_component"
        mqttPassword: "Dr0ne-C0ntrol-Compon3nt"
    simulate:
      disableExecutionModeChange: true
      disableOccupationCheck: true
