logging:
  level:
    org.springframework.boot.autoconfigure: INFO
server:
  port: 8088
  accessibleEndpoint: http://localhost:8088
management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"
basys:
  aasRegistry:
    type: dotaas
    service:
      connectionString: http://localhost:8020
  eventTransmitter:
    type: mqtt
    service:
      implementationJavaClass: de.dfki.cos.basys.aas.event.mqtt.MqttEventTransmitter
      connectionString: tcp://localhost:1883
  opcuaServer:
    certsFolder: ./certs
    tcpPort: 12685
    httpsPort: 8443
  controlcomponent:
    id: ur10_1
    name: UR10-1
    operationModeJavaPackage: de.dfki.cos.basys.p4p.controlcomponent.ur.opmodes
    executionMode: SIMULATE
    auto:
      disableExecutionModeChange: false
      disableOccupationCheck: false
      service:
        implementationJavaClass: de.dfki.cos.basys.p4p.controlcomponent.ur.service.UrServiceImplRPC
        connectionString: http://10.2.1.16:8081
    simulate:
      disableExecutionModeChange: true
      disableOccupationCheck: true
      service:
        implementationJavaClass: de.dfki.cos.basys.p4p.controlcomponent.ur.service.UrServiceImplROS
        connectionString: ws://localhost:9100
        movSymServerName: /movsym/ur10_1
        movSymActionName: /simrk40_msgs/MoveToSymbolicPositionAction
        ppSymServerName: /ppsym/ur10_1
        ppSymActionName: /simrk40_msgs/PickAndPlaceSymbolicAction
