basys:
  controlcomponent:
    simulate:
      service:
        implementationJavaClass: de.dfki.cos.basys.p4p.controlcomponent.ur.service.UrServiceImplROS
        connectionString: ws://localhost:9100
        serverName: movsym_action
        actionNameMove: simrk40_msgs/MoveToSymbolicPositionAction
