spring:
  application:
    name: materialoutput_1
logging:
  level:
    org.springframework.boot.autoconfigure: INFO
server:
  port: 8088
  accessibleEndpoint: http://localhost:8088
basys:
  opcuaServer:
    certsFolder: ./certs
    tcpPort: 12685
    httpsPort: 8443
  controlcomponent:
    id: materialoutput_1
    name: MaterialOutput-1
    operationModeJavaPackage: de.dfki.cos.basys.p4p.controlcomponent.virtual.opmodes.materialoutput
    executionMode: SIMULATE
    auto:
      disableExecutionModeChange: false
      disableOccupationCheck: false
    simulate:
      disableExecutionModeChange: true
      disableOccupationCheck: true