logging:
  level:
    org.springframework.boot.autoconfigure: INFO
server:
  port: 8088
  accessibleEndpoint: http://localhost:8088
basys:
  aasRegistry:
    type: dotaas
    service:
      connectionString: http://localhost:8080
  eventTransmitter:
    type: mqtt
    service:
      implementationJavaClass: de.dfki.cos.basys.aas.event.mqtt.MqttEventTransmitter
      connectionString: tcp://localhost:1883
  opcuaServer:
    certsFolder: ./certs
    tcpPort: 12685
    httpsPort: 8443
  controlcomponent:
    id: smartwatch_1
    name: SmartWatch-1
    operationModeJavaPackage: de.dfki.cos.basys.p4p.controlcomponent.smartwatch.opmodes
    executionMode: SIMULATE
    auto:
      disableExecutionModeChange: false
      disableOccupationCheck: false
      service:
        implementationJavaClass: de.dfki.cos.basys.p4p.controlcomponent.smartwatch.service.NotificationServiceImpl
        connectionString: mq3t.rpc://smartwatch-lg-3691.mrk40.dfki.lan:9030
    simulate:
      disableExecutionModeChange: true
      disableOccupationCheck: true