basys:
  opcuaServer:
    certsFolder: ./certs
    tcpPort: 12685
    httpsPort: 8443
  controlcomponent:
    id: smartwatch_1
    name: SmartWatch-1
    operationModeJavaPackage: de.dfki.cos.basys.p4p.controlcomponent.smartwatch.opmodes
    initialExecutionMode: SIMULATE
    executionModes:
      auto:
        executionModeChangeDisabled: false
        occupationCheckDisabled: false
        service:
          implementationJavaClass: de.dfki.cos.basys.p4p.controlcomponent.smartwatch.service.NotificationServiceImpl
          connectionString: mq3t.rpc://smartwatch-lg-3691.mrk40.dfki.lan:9030
      simulate:
        executionModeChangeDisabled: true
        occupationCheckDisabled: true